Feature/jac fetcher migration
distributed-lab/web-kit pull request #10
Opened 2023-04-11 11:43 UTC by napalmpapalam

2023-04-12 10:42 UTC, lukachi approved these changes

2023-04-13 08:42 UTC, ArtSuslov requested changes

2023-04-13 08:42 UTC, ArtSuslov commented on packages/fetcher/README.md
>  ```
fix formatting

2023-04-13 08:42 UTC, ArtSuslov commented on packages/jac/src/errors/server-errors.ts
> +      this.message = 'Request contains some errors. Check "nestedErrors"'
some -> multiple

2023-04-13 08:42 UTC, ArtSuslov commented on packages/jac/src/json-api.ts
> +    body?: JsonApiClientRequestBody,
is it allowed to send `{data: undefined}`?

2023-04-17 08:00 UTC, napalmpapalam commented on packages/jac/src/json-api.ts
> +    body?: JsonApiClientRequestBody,
yes, u can have a post endpoint which doesn't require body

2023-04-17 08:00 UTC, napalmpapalam commented on packages/jac/src/errors/server-errors.ts
> +      this.message = 'Request contains some errors. Check "nestedErrors"'
fixed

2023-04-17 08:00 UTC, napalmpapalam commented on packages/fetcher/README.md
>  ```
fixed

2023-04-17 08:42 UTC, ArtSuslov approved these changes

2023-04-17 08:45 UTC, merged