Feature/w3p
distributed-lab/web-kit pull request #12
Opened 2023-04-22 14:12 UTC by lukachi

2023-04-22 16:09 UTC, napalmpapalam requested changes

2023-04-22 16:09 UTC, napalmpapalam commented on .gitignore
> +packages/**/node_modules/
not needed

2023-04-22 16:09 UTC, napalmpapalam commented on CHANGELOG.md
> +- `@distributedlab/w3p` - wrapper for web3 providers
```suggestion
- - `root`: Package `@distributedlab/w3p` - wrapper for web3 providers
```

2023-04-22 16:09 UTC, napalmpapalam commented on package.json
> +    "ts-jest": "^29.0.5",
remove

2023-04-22 16:09 UTC, napalmpapalam commented on packages/w3p/.npmignore
> +src/test/
src/tests/

2023-04-22 16:09 UTC, napalmpapalam commented on packages/w3p/README.md
> +
```suggestion
The Web3 provider wrapper with a common interface to easily interact with different types of blockchains.

```

2023-04-22 16:09 UTC, napalmpapalam commented on packages/w3p/README.md
> +await providerDetector.init()
let's wrap into the fn

2023-04-22 16:09 UTC, napalmpapalam commented on packages/w3p/README.md
> +  [PROVIDERS.Metamask]: MetamaskProvider as ProviderProxyConstructor,
why u need as here?

2023-04-22 16:09 UTC, napalmpapalam commented on packages/w3p/README.md
> +} as Record<PROVIDERS, ProviderProxyConstructor>
Let's export this type ` Record<PROVIDERS, ProviderProxyConstructor>`

2023-04-22 16:09 UTC, napalmpapalam commented on packages/w3p/src/enums/near-wallet-action-type.ts
> +export enum NEAR_WALLET_ACTION_TYPE {
it's not wallet action type, let's rename to the `NEAR_ACTIONS` and add all actions https://nomicon.io/RuntimeSpec/Actions

2023-04-22 16:09 UTC, napalmpapalam commented on packages/w3p/src/enums/providers.ts
> +// Values must be lowercase because we lowercase them in Web3.init
what?

2023-04-22 16:09 UTC, napalmpapalam commented on packages/w3p/src/enums/providers.ts
> +  // Not implemented yet
does it?

2023-04-22 16:09 UTC, napalmpapalam commented on packages/w3p/src/enums/providers.ts
> +  AfterTxConfirmed = 'after-tx-confirmed',
```ts
BeforeTxSent = 'before-tx-sent',
TxSent = 'tx-sent',
TxConfirmed = 'tx-confirmed',
```

2023-04-22 16:09 UTC, napalmpapalam commented on packages/w3p/src/enums/rpc-error-codes.ts
> +  unrecognizedChain = 4902,
why do these keys start from lowercase char? same in the another ones

2023-04-22 16:09 UTC, napalmpapalam commented on packages/w3p/src/errors/provider.ts
> +
```ts
export class ProviderNotInitializedError extends RuntimeError {
  public name = 'ProviderNotInitializedError'
  constructor(message = 'Provider is not initialized') {
    super(message)
  }
}
```

2023-04-22 16:09 UTC, napalmpapalam commented on packages/w3p/src/provider.ts
> + *
`await provider.connect()`

2023-04-22 16:09 UTC, napalmpapalam commented on packages/w3p/src/provider.ts
> +    if (provider.instance) {
invert

2023-04-22 16:09 UTC, napalmpapalam commented on packages/w3p/src/provider.ts
> +    }
`await this.#proxy?.disconnect?.()`

2023-04-22 16:09 UTC, napalmpapalam commented on packages/w3p/src/provider.ts
> + * const phantomProvider = await createProvider(PhantomProvider, { providerDetectorInstance })
let's rename opt to just `providerDetector` and fix `await new providerDetector().init()` to `await new ProviderDetector().init()`

2023-04-22 16:09 UTC, napalmpapalam commented on packages/w3p/src/providers/raw/near-raw-provider.ts
> +          type: NEAR_WALLET_ACTION_TYPE.functionCall,
we should give abillity to provider it otherwise set functionCall by default

2023-04-22 16:09 UTC, napalmpapalam commented on packages/w3p/src/types/provider.ts
> +  | Deferrable<TransactionRequest>
near body?

2023-04-22 16:10 UTC, napalmpapalam commented on packages/w3p/src/providers/raw/near-raw-provider.ts
> +          type: NEAR_WALLET_ACTION_TYPE.functionCall,
u could send tx to not only call contract, but create account etc

2023-04-22 16:43 UTC, ArtSuslov requested changes

2023-04-22 16:43 UTC, ArtSuslov commented on packages/w3p/src/helpers/eth.ts
> +import { ethers, type providers } from 'ethers'
to reduce size better to import hexlify from '@ethersproject/bytes'

2023-04-22 16:43 UTC, ArtSuslov commented on packages/w3p/src/provider-detector.ts
> +  #initiated = false
isInitiated

2023-04-22 16:43 UTC, ArtSuslov commented on packages/w3p/src/provider-detector.ts
> +    await sleep(500)
mb there is a way to get rid of those sleeps? like subscribing to `ethereum#initialized` event in MM, maybe there are such events in other providers

2023-04-22 16:43 UTC, ArtSuslov commented on packages/w3p/src/provider-detector.ts
> +    await sleep(500)
this one looks like redundant

2023-04-24 10:34 UTC, ArtSuslov approved these changes

2023-04-24 12:00 UTC, merged