update w3p docs
distributed-lab/web-kit pull request #26
Opened 2023-05-28 16:37 UTC by lukachi

2023-05-29 08:06 UTC, napalmpapalam requested changes

2023-05-29 08:06 UTC, napalmpapalam commented on packages/w3p/examples/multiple-providers.ts
> +} from '@/helpers'
remove commented code

2023-05-29 08:06 UTC, napalmpapalam commented on packages/w3p/examples/multiple-providers.ts
> +// type SUPPORTED_PROVIDERS = EXTERNAL_PROVIDERS | PROVIDERS
?

2023-05-29 08:06 UTC, napalmpapalam commented on packages/w3p/examples/multiple-providers.ts
> +      // }
do examples inside if the /** */

2023-05-30 11:21 UTC, napalmpapalam approved these changes

2023-05-30 11:28 UTC, ArtSuslov approved these changes

2023-05-30 11:28 UTC, merged