Feature: BN 2.0
distributed-lab/web-kit pull request #34
Opened 2023-07-08 13:38 UTC by napalmpapalam

2023-07-11 11:44 UTC, ardier16 requested changes

2023-07-11 11:44 UTC, ardier16 commented on packages/tools/src/helpers/general.ts
> +  return Boolean(value.match(/^(-?)(\d*)$/))
'-' is integer string

2023-07-11 11:44 UTC, ardier16 commented on packages/tools/src/helpers/general.ts
> +  if (expression) throw new RuntimeError(message)
why assert works vice versa comparing to Node assert?
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions

2023-07-11 11:44 UTC, ardier16 commented on packages/tools/src/types/bn.ts
> +  decimalSeparator?: string
thx cap 🫡

2023-07-11 11:44 UTC, ardier16 commented on packages/tools/src/const/bn.ts
> +export const NUMBER_REGEX = /^(-?)(\d*)\.?(\d*)$/
'-' and '-.' are valid numbers here

2023-07-11 11:44 UTC, ardier16 commented on packages/tools/src/const/bn.ts
> +export const HEX_REGEX = /^0x[0-9a-f]+$/i
why not uppercased `A-F` too?

2023-07-11 11:44 UTC, ardier16 commented on packages/tools/src/bn/format.ts
> +  return result.endsWith(char) ? result.slice(0, -1) : result
```
> insertCharEveryN('berta', 'a', 3)
< 'berat'
```

2023-07-11 11:44 UTC, ardier16 commented on packages/tools/src/bn/format.ts
> +  }, '')
may be
```const result = value.replace(new RegExp(`(.{${n}})`, 'g'), `$1${char}`)```

2023-07-11 11:44 UTC, ardier16 commented on packages/tools/src/bn/format.ts
> +  const negative = whole.startsWith('-') ? '-' : ''
maybe `sign` instead?

2023-07-11 11:44 UTC, ardier16 commented on packages/tools/src/bn/format.ts
> +  if (decimals) {
duplicate conditional
let's either use ternary or else

2023-07-11 11:44 UTC, ardier16 commented on packages/tools/src/bn/assertions.ts
> +  assert(expression, message)
IMO `if (op === BN_ASSERT_DECIMALS_OP.GREATER) { assert(...) } else { assert(...) }` or `if return` is more readable here as it does not require to keep in mind the context

2023-07-11 11:44 UTC, ardier16 commented on packages/tools/src/bn/decimals.ts
> +  decimals: number,
why we pass `decimals` to function `toDecimals`? 🤔

2023-07-11 11:44 UTC, ardier16 commented on packages/tools/src/bn/decimals.ts
> +  currentDecimals: number,
why it's `actualDecimals` above, but `currentDecimals` here?

2023-07-11 11:44 UTC, ardier16 commented on packages/tools/src/bn/parsers.ts
> +  let val = _value.trimStart().trimEnd()
why not just `trim`? 🤔

2023-07-11 11:50 UTC, napalmpapalam commented on packages/tools/src/const/bn.ts
> +export const HEX_REGEX = /^0x[0-9a-f]+$/i
i flag there

2023-07-11 12:01 UTC, napalmpapalam commented on packages/tools/src/helpers/general.ts
> +  return Boolean(value.match(/^(-?)(\d*)$/))
fixed

2023-07-11 12:02 UTC, napalmpapalam commented on packages/tools/src/types/bn.ts
> +  decimalSeparator?: string
removed

2023-07-11 12:21 UTC, napalmpapalam commented on packages/tools/src/const/bn.ts
> +export const NUMBER_REGEX = /^(-?)(\d*)\.?(\d*)$/
fixed

2023-07-11 12:26 UTC, napalmpapalam commented on packages/tools/src/bn/format.ts
> +  }, '')
yea

2023-07-11 12:26 UTC, napalmpapalam commented on packages/tools/src/bn/format.ts
> +  const negative = whole.startsWith('-') ? '-' : ''
ye

2023-07-11 12:29 UTC, napalmpapalam commented on packages/tools/src/bn/format.ts
> +  if (decimals) {
+

2023-07-11 12:31 UTC, napalmpapalam commented on packages/tools/src/bn/decimals.ts
> +  currentDecimals: number,
fiixed

2023-07-11 12:31 UTC, napalmpapalam commented on packages/tools/src/bn/parsers.ts
> +  let val = _value.trimStart().trimEnd()
fixed

2023-07-11 12:47 UTC, napalmpapalam commented on packages/tools/src/bn/format.ts
> +  return result.endsWith(char) ? result.slice(0, -1) : result
fixed

2023-07-11 12:48 UTC, napalmpapalam commented on packages/tools/src/helpers/general.ts
> +  if (expression) throw new RuntimeError(message)
fixed

2023-07-11 12:50 UTC, napalmpapalam commented on packages/tools/src/bn/assertions.ts
> +  assert(expression, message)
fixed

2023-07-11 12:57 UTC, napalmpapalam commented on packages/tools/src/bn/decimals.ts
> +  decimals: number,
fixed

2023-07-11 15:08 UTC, ardier16 approved these changes

2023-07-11 16:59 UTC, ArtSuslov requested changes

2023-07-11 16:59 UTC, ArtSuslov commented on packages/tools/src/bn/decimals.ts
> +  currentDecimals: number,
BigInt argument should be integer, passing float number will throw (everywhere where you format number to big int)

2023-07-11 16:59 UTC, ArtSuslov commented on packages/tools/src/bn/bn.ts
> +   * const oneEth = BN.fromBigInt(1, 18)
fromRaw

2023-07-11 16:59 UTC, ArtSuslov commented on packages/tools/src/bn/bn.ts
> +    return new BN(min.raw, min.config)
do you actually need to create new BN? min is already an instance of BN

2023-07-11 16:59 UTC, ArtSuslov commented on packages/tools/src/bn/bn.ts
> +    return new BN(max.raw, max.config)
same

2023-07-11 16:59 UTC, ArtSuslov commented on packages/tools/src/bn/bn.ts
> +    assert(expression, 'sqrt requires precision to be even number')
discussed

2023-07-11 16:59 UTC, ArtSuslov commented on packages/tools/src/bn/bn.ts
> +  public pow(exponent: number): BN {
float validation

2023-07-12 06:48 UTC, napalmpapalam commented on packages/tools/src/bn/bn.ts
> +  public pow(exponent: number): BN {
fixed

2023-07-12 06:48 UTC, napalmpapalam commented on packages/tools/src/bn/bn.ts
> +    return new BN(max.raw, max.config)
fixed

2023-07-12 06:48 UTC, napalmpapalam commented on packages/tools/src/bn/bn.ts
> +    return new BN(min.raw, min.config)
fixed

2023-07-12 06:48 UTC, napalmpapalam commented on packages/tools/src/bn/bn.ts
> +   * const oneEth = BN.fromBigInt(1, 18)
fixed

2023-07-12 06:48 UTC, napalmpapalam commented on packages/tools/src/bn/decimals.ts
> +  currentDecimals: number,
fixed

2023-07-12 07:24 UTC, ArtSuslov approved these changes

2023-07-12 07:25 UTC, merged